github: LukeSavefrogs
patreon: LukeSavefrogs
ko_fi: lukesavefrogs
custom:
  # PayPal donation button is superior to a paypal.me link because it
  # additionally:
  #   - accepts credit cards without a need to create a PayPal account
  #   - allows monthly subscriptions (requires a PayPal account)
  # However, the URL is rather lengthy and GitHub shows it in full in the
  # Sponsor modal popup.
  - https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=RN3XMAHA8FZEE&source=url
